### ISSUE TITLE
is grabFrame necessary?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/mediacapture-image#144]
from @w3ctag 's [review](https://github.com/w3ctag/spec-reviews/issues/133#issuecomment-270259285) @travisleithead:
> Is 'grabFrame' really necessary? Isn't this already possible using a video/canvas element?

**Comment by miguelao** [comment]
It's possible to have a `MediaStream` and retrieve its contents via casting it to a `<video>`, drawing the contents of the latter to a `<canvas>` to then retrieve the pixels via its context (let's call the this the indirect path) but:
- it's inefficient: the described indirect path needs a `<video>`, a `<canvas>` and a `CanvasRenderingContext2D`.
- `<canvas>` will in all likelihood draw using the system's GPU, which further reduces the speed of the indirect path due to the round trip to the GPU plus the necessary texture resolutions.
- `<canvas>` has more possibilities of becoming tainted than an `ImageCapture` created out of a `MediaStream`

**Comment by miguelao** [comment]
Related to this, @mounirlamouri argued in #84 that `grabFrame()` might be a better citizen of `MediaStreamTrack`.  

A similar pattern was used for `<canvas>.captureStream()` where a [`CanvasCaptureMediaStreamTrack`](https://w3c.github.io/mediacapture-fromelement/#dom-canvascapturemediastreamtrack) was introduced in order to have a single method [`requestFrame()`](https://w3c.github.io/mediacapture-fromelement/#dom-canvascapturemediastreamtrack-requestframe).  

We could do something similar here, if that would address the concerns of @mounirlamouri and @travisleithead.  @alvestrand, @gmandyam what do you think?

**Comment by alvestrand** [comment]
.... except that the entity getting the frame is a consumer of the MediaStreamTrack, not the producer as it was in the canvas case, so the model doesn't quite fit. We want to grab frames from any sort of track, without having to have the frame-grabbing travel all the way to the producer having to know that this is a track of the type you can grab frames from.

Once upon a time we had separate IDL classes for VideoTrack and AudioTrack, but after a year of nobody finding any API we wanted to have different on the two, we went ahead and merged them. Separating them back out would be a pain in the posterior, I think.

To me it seems simpler to have grabFrame() be a method on the object you connect a MediaStreamTrack to, just the way it's currently specified.

But at the end of the day, it's all control surface. The real data travels by whatever means makes sense for the implementation.

**Comment by gmandyam** [comment]
@miguelao - From an API perspective I am indifferent as to where grabFrame() lives, but I see the point that @alvestrand is making as well.  Given that, it does not seem to add much value to hang the method off of MediaStreamTrack.

**Comment by miguelao** [comment]
I agree with both previous comments, so closing this issue. Thanks!
