### ISSUE TITLE
Use DOMPoint instead of Point2D?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/mediacapture-image#145]
from @w3ctag 's [review](https://github.com/w3ctag/spec-reviews/issues/133#issuecomment-270259285) @travisleithead:
> Consider allowing a DOMPoint in places where a Point2D dictionary could be used (DOMPoint from http://www.w3.org/TR/geometry-1/#DOMPoint). The DOMPoint handles points in 3d space, but the 'z' and 'w' coordinates are not required, and this may be useful for platform consistency.

**Comment by miguelao** [comment]
[`DOMPoint`](http://www.w3.org/TR/geometry-1/#DOMPoint) is an interface needing all its attributes `x`,`y`,`z`,`w` (I don't see any indication of `z` and `w` being not required), whereas `Point2D` is a dictionary with just `x` and `y`.

Moreover, [`DOMPoint`](http://www.w3.org/TR/geometry-1/#DOMPoint)  is not 'just' a cartesian point but a 3D point with a perspective `w` attached to it (although this is by default `1.0`) --The reason for this pseudo-quaternion situation is that `DOMPoint` is meant to play nicely with transformation `DOMMatrix`es.

Using `DOMPoint` would be confusing for users, since two of the said `DOMPoint` attributes are not used in this case but they actually relate to the mathematics of perspective cameras.  Perhaps `DOMPoint` should be renamed to `DOMPoint3D` and a `DOMPoint2D` added to the Geometry interfaces Spec.  

Finally, if any of the Geometry Interfaces would be needed, [`DOMRect`](https://www.w3.org/TR/geometry-1/#DOMRect) would be the least removed one.

**Comment by domenic** [comment]
Because Point2D is only used in dictionaries, the distinction is very slight. If DOMPointInit was used (not DOMPoint; that would be bad) then inputs like `{ x: 1, y: 2, get z() { throw new Error("z"); } }` would throw when being converted to a DOMPointInit, even though the plan is to ignore the z (and w). Whereas in the current spec, given such input the z (and w) are ignored, so it would not throw. So I think Point2D as used here is the right choice.

However, if the points were ever exposed externally (e.g. as attribute values or method return values), then DOMPoint might be a better choice, for platform harmony. I can't find any such instances in the spec right now.

**Comment by miguelao** [comment]
`getSettings()` returns a [`MediaTrackSettings`](https://w3c.github.io/mediacapture-image/#mediatracksettings-section) that has a `sequence<Point2D>` representing the current points/areas used for A3 calculation.

**Comment by miguelao** [comment]
@domenic I'm closing this issue, plz reopen or shout if this is not intended, thanks!

**Comment by travisleithead** [comment]
Works for me.
