### ISSUE TITLE
PhotoSettings members have misleading names

### ISSUE THREAD

**Issue by alexshalamov** [w3c/mediacapture-image#159]
Many members in `PhotoSettings` dictionary have misleading names e.g. `MeteringMode focusMode; `Would it be possible to, at least, typedef those? For example:

```
typedef (MeteringMode) FocusingMode;
typedef (MeteringMode) WhiteBalanceMode;
```

**Comment by yellowdoge** [comment]
I'm not sure how much would the gain in specificity be offset by the loss in generality, i.e. `MeteringMode` is the same on purpose to reflect that these controls behave in a similar never/once/always way.  

(Closing tentatively since I haven't seen much action in this issue, will reopen if needed)
