### ISSUE TITLE
Make PhotoCapabilities interface properties nullable

### ISSUE THREAD

**Issue by alexshalamov** [w3c/mediacapture-image#160]
It would be easier to represent capabilities that are not supported by the camera.

**Comment by miguelao** [comment]
After landing the Constrainable Pattern -aligned version of the Spec, [`PhotoCapabilities`](https://w3c.github.io/mediacapture-image/##photocapabilities-section) are very reduced:
```
interface PhotoCapabilities {
  readonly attribute FillLightMode      fillLightMode;
  readonly attribute MediaSettingsRange imageHeight;
  readonly attribute MediaSettingsRange imageWidth;
  readonly attribute sequence<boolean>  redEyeReduction;
};
```

(actually, `fillLightMode` should be a `sequence<FillLightMode>`, ugh, I'll file an issue)

That said, all the other capabilities are expressed as a `partial dictionary` [`MediaTrackCapabilities`](https://w3c.github.io/mediacapture-image/#mediatrackcapabilities-section), so that features are not present if not supported, which probably addresses your concern.  Tentatively closing this issue because of this.

Note that you can try the latest Spec status in Chrome Canary with the chrome://flags/#enable-experimental-web-platform-features flag on.

**Comment by alexshalamov** [comment]
@miguelao thanks, moving optional caps to partial dictionary should do it.
