### ISSUE TITLE
Are brightness, contrast and saturation settings needed?

### ISSUE THREAD

**Issue by alexshalamov** [w3c/mediacapture-image#161]
Brightness, contrast and saturation are rarely supported by the platform APIs and might be not that useful and produce side-effects, for example, if brightness is used together with exposure compensation / contrast.

**Comment by miguelao** [comment]
On the contrary, non mobile platforms support these four capabilities (namely: brightness, contrast, saturation and sharpness) pervasively because they are defined in the [UVC 1.5 Class specification](http://www.usb.org/developers/docs/devclass_docs/) (pdf [here](https://tinyurl.com/uvc-1-5-specification), see Section 4.2.2.3.2 etc). (see https://goo.gl/QfW355).  Since the vast majority of WebCams on non-Android world are USB, these four are very common.  

The way they interact with other controls is exactly as you would expect when playing with e.g. [guvcview](https://en.wikipedia.org/wiki/Guvcview) or [qv4l2](http://manpages.ubuntu.com/manpages/xenial/man1/qv4l2.1.html) in Linux, i.e.: all control is left to the user.

**Comment by alexshalamov** [comment]
@miguelao thanks for explanation, seems to be useful feature for web cams.
