### ISSUE TITLE
Current settings are not exposed

### ISSUE THREAD

**Issue by mounirlamouri** [w3c/mediacapture-image#167]
The settings used by the camera are not exposed which means that a website will have to set the settings to a default value in order to show a UI to control them which isn't ideal if a user has preferred settings set up on the system. For example, if as a user I prefer to have flash set to disabled, I would prefer my web application to start in this mode.

**Comment by alvestrand** [comment]
getSettings() is available for those properties that are properties of the track.

**Comment by miguelao** [comment]
The photo-specific ones 
```webidl
dictionary PhotoSettings {
  FillLightMode   fillLightMode;
  double          imageHeight;
  double          imageWidth;
  boolean         redEyeReduction;
};
```
don't need to be read back because their application is only needed when an exposure is taking place, and because reading them back is idempotent to writing them when taking a picture. In your case, if an app wants to have the flash set to, e.g. disabled, it's the same to force it to `"off"` than to read back its current setting, if any, and then, if needed, modify it upon `takePhoto()`.   Also, `imageWidth` and `imageHeight` can be read back from the capture photo.

**Comment by mounirlamouri** [comment]
@alvestrand `getSettings` doesn't return the "photo" settings, does it?

@miguelao I think I have a hard time to follow your answer. My concern is that these settings can't be read without being changed which sounds like an issue. Are you saying that it's not a normal use case?

**Comment by yellowdoge** [comment]
Ah, uh, sorry, there was indeed a gap between moving things out of `getPhotoCapabilities()` and reducing `MediaSettingsRange`, if you read the description of the first:

> getPhotoCapabilities() is used to retrieve the ranges of available configuration options and their current setting values, if any. 

but `MediaSettingsRange` has no `current` member anymore.  I'll add a `getPhotoSettings()` method and correct the literature.
