### ISSUE TITLE
getCapabilities needs to be async

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c/mediacapture-image#169]
As `MediaTrackCapabilities` can't be retrieved until a while after opening the device, it would be better if `getCapabilities` returns a promise so that it is always filled:

```js
const capabilities = await track.getCapabilities();
```

**Comment by miguelao** [comment]
Note that [`getCapabilities()`](https://w3c.github.io/mediacapture-main/#dom-constrainablepattern-getcapabilities()) is part of the `mediacapture-streams` specification and that here we are limited by it.

That said, probably the idea in `mediacapture-streams` was to collect the capabilities once and only upon [`MediaDevices.getUserMedia()`](https://w3c.github.io/mediacapture-main/#mediadevices-interface-extensions) which is Promise-based:

`Promise<MediaStream>           getUserMedia(optional MediaStreamConstraints constraints);`

but, since in Chromium only the non-Promise based is implemented, we're in this situation.

**Comment by alvestrand** [comment]
getUserMedia() is async in all its versions.

**Comment by beaufortfrancois** [comment]
@alvestrand Good news.
@miguelao Maybe that means we can fix that then.

**Comment by beaufortfrancois** [comment]
@miguelao (gentle ping)

**Comment by miguelao** [comment]
`getCapabilities()` is innocent - Chrome implementation shouldn't need the timeout, but it needs it ATM -- let's track it in a Chromium Issue tracker, I'll add one to the B[link>ImageCapture component](https://bugs.chromium.org/p/chromium/issues/list?can=2&q=component%3ABlink%3EImageCapture+&sort=-modified&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids)

**Comment by beaufortfrancois** [comment]
For future reference, here's the chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=711524

**Comment by yellowdoge** [comment]
Since this applies to the Cr implementation only, and there's a tracking bug there (https://crbug.com/711524), let's close this bug.
