### ISSUE TITLE
Faster MediaStream ImageCapture.takePhoto on 'desktop' source

### ISSUE THREAD

**Issue by developer239** [w3c/mediacapture-image#197]
I get MediaStream object from `navigator.mediaDevices.getUserMedia`:

```
navigator.mediaDevices.getUserMedia({
  audio: false,
  video: {
    mandatory: {
      chromeMediaSource: 'desktop',
      chromeMediaSourceId: source.id,
      minWidth: 1000,
      maxWidth: 1000,
      minHeight: 1000,
      maxHeight: 1000,
    },
  },
})
.then((stream) => {
```

I am trying to get node Buffer of **every** a still frame using ImageCapture:

```
  const track = stream.getVideoTracks()[0];
  const capturedImage = new ImageCapture(track);

  capturedImage // This takes 200ms for 1000x1000 that is only 5 FPS
    .takePhoto()
    .then(blob => {
      toBuffer(blob, function (err, buffer) { // 1.5 ms
        if (err) throw err;
          // TODO: Do some opencv magic with node buffer
      });
    })
    .catch(error => console.error('takePhoto() error:', error));
```

But it takes awfully long to takePhoto. Is it possible to make the process faster? Can I somehow access the `MediaStream` directly as `readable stream` in nodejs?

**Comment by developer239** [comment]
This is what I ended up doing. It is actually a lot more performant.

```
      }).then((stream) => {
        const video = document.createElement('video');
        video.srcObject = stream;
        video.onloadedmetadata = () => {
          video.play();
          setInterval(() => {
            const canvas = document.createElement('canvas');
            canvas.getContext('2d').drawImage(video, 0, 0, 800, 800);
            canvas.toBlob(blob => {
              toBuffer(blob, function (err, buffer) {
                if (err) throw err;
                // do some magic with buffer
              });
            });
          }, 40);
        };
```

**Comment by alvestrand** [comment]
If you want the stream of video (encoded), use a MediaStreamRecorder.
If you want to access the data of every frame, I think you are going to need a fairly hefty amount of CPU; the canvas solution is probably the faster one - I see you're asking for 25 fps; did you get that in practice?
TakePhoto is supposed to get you an encoded image, so will spend time re-encoding the image into your desired format; that might be part of the extra overhead.

Still 200 ms to encode a frame is a fair chunk of time, if correctly measured. How did you measure it?

**Comment by developer239** [comment]
@alvestrand It would be cool to have something like this though:

```
  stream // MediaStream or CaptureImage(MediaStream)
    .readStream(blob => { // blob or even nodejs buffer I am not sure how would that work in web environment
      toBuffer(blob, function (err, buffer) {
        if (err) throw err;
          // TODO: Do some magic with nodejs buffer
      });
    })
    .catch(error => console.error('takePhoto() error:', error));
```

By the way I used `console.time` and `console.end` to measure the performance.

**Comment by yellowdoge** [comment]
@developer239:
Have you tried using [`grabFrame()`](https://w3c.github.io/mediacapture-image/#dom-imagecapture-grabframe) instead of `takePhoto()` ? It is faster, in part because it doesn't compress the data for you into a `Blob`, but instead gives you an `ImageBitmap`. More in about [Chrome in particular](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/imagecapture/README.md?type=cs&q=grabframe%5C(%5C)&sq=package:chromium&l=60).

Re. creating a `MediaStream` `readableStreamReader`, I put up a proposal in the [WICG](https://discourse.wicg.io/t/rfc-proposal-for-integration-streams-mediastreamtrack-api/2256) and even had a playground [Chromium CL](https://crrev.com/c/571382) :-)

**Comment by yellowdoge** [comment]
ping @developer239

**Comment by developer239** [comment]
@yellowdoge I ended up doing something like this: https://stackoverflow.com/questions/48250790/faster-mediastream-imagecapture-read-media-stream-as-buffer-in-nodejs/48253845#48253845 :)

I am not sure but I feel like grabFrame was actually pretty slow. :D

**Comment by yellowdoge** [comment]
@developer239 I think the key here is that the source is a 'desktop', which makes up for a special type of VideoFrames passing along the `MediaStreamTrack`, namely ones backed by Textures, i.e. they stay inside the GPU driver, so when the `Context2D` creates a `Blob`, it's probably using faster GPU resources, whereas `grabFrame()` will use Skia to pull the data out of the Texture, which is slower. 

Also consider that the `blob` you get might be lazily evaluated, so at the time you get to `//do some magic` you might not quite have the data, but if you were to, e.g. save the `blob`, then you'll hit a delay. That'd be cool to double check.  Otherwise this seems to be more a Chrome issue than a Spec issue. So, closing it. Thanks for your feedback!
