### ISSUE TITLE
[PTZ] Should `applyConstraints` request permission?

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c/mediacapture-image#223]
I wonder why `applyConstraints ()` should prompt users for PTZ access when web developers have no way to provide meaningful PTZ constraints as they don' have access to PTZ settings/capabilities.

Shall we only prompt users with PTZ from a gUM call instead, or permissions.request API?

@reillyeon @riju @eehakkin

**Comment by reillyeon** [comment]
Would `applyConstraints()` support the `{pan: true, tilt: true, zoom: true}` syntax we added for `getUserMedia()` to solve this problem? Otherwise only prompting from `getUserMedia()` and `permission.request()` seems reasonable to me for the reason you state.

**Comment by beaufortfrancois** [comment]
I'm not sure if the `{pan: true, tilt: true, zoom: true}` syntax would be compliant for applyConstraints?
@guidou would you know by any chance?

**Comment by guidou** [comment]
That syntax is valid, except that pan/tilt/zoom are numeric properties, not boolean.
Chrome's implementation of applyConstraints currently does not support it, but that's a bug.

**Comment by beaufortfrancois** [comment]
We added specifically this at https://w3c.github.io/mediacapture-image/#dom-mediatrackconstraintset-pan. Does that help?
```
  (boolean or ConstrainDouble) pan;
  (boolean or ConstrainDouble) tilt;
  (boolean or ConstrainDouble) zoom;
```

**Comment by eehakkin** [comment]
> I wonder why `applyConstraints ()` should prompt users for PTZ access when web developers have no way to provide meaningful PTZ constraints as they don' have access to PTZ settings/capabilities.

My original thinking was that web developers always have access PTZ settings/capabilities, so in that situation web developers would have had a way to provide meaningful PTZ constraints.

> I'm not sure if the `{pan: true, tilt: true, zoom: true}` syntax would be compliant for applyConstraints?

After the new "true" semantics, that is compliant.

Would it be a valid use case that a web site checks that is has a camera permission but not a ptz permission and thus starts a video stream using getUserMedia without {pan: true, ...} in order to get the stream instantly without prompts and then later issues applyConstraint({pan: true, ...}) (by user request perhaps) in order to upgrade the current video stream to PTZ stream?

**Comment by beaufortfrancois** [comment]
@andypaicu FYI

**Comment by reillyeon** [comment]
That kind of upgrade scenario is worth considering but it has UX consequences. It doesn't seem compatible with the UX design that Chrome is considering which assumes that the camera stream and PTZ are being considered simultaneously and will automatically ignore the request for PTZ if the connected camera does not support it.

**Comment by beaufortfrancois** [comment]
What shall we do then?

**Comment by reillyeon** [comment]
Calling `applyConstraints({pan: true, tilt: true, zoom: true}}` could request PTZ permission but I worry that if we apply the existing automatic ignore logic then that would expose capabilities of the user's device through the immediate denial. The best option seems to be to present the prompt to the user whether or not they have a PTZ camera available.

The purpose of ignoring the request for PTZ in `getUserMedia()` is to avoid prompting users for a capability their hardware doesn't support on every camera permission request. The use case for `applyConstraints()` is different. As @eehakkin suggested, it could be used by a site with an explicit "enable PTZ" button.

**Comment by andypaicu** [comment]
We have precedent in Chrome for delaying an automatic reply to a permission request to prevent deducing user state (in particular, notification permission requests in incognito). We can use that same approach here, if deemed necessary. Is the concern that this would help with fingerprinting users? I'm not very familiar with the media API so I'm not entirely sure how big the fingerprinting surface is already without PTZ and how much PTZ adds.

On the other hand, presenting a user with a prompt for a capability they do not have seems like an unnecessary cognitive load, probably confusing and also different than how all other permissions work (you don't get camera prompts if you don't actually have a camera for example) and something that I would like to avoid if at all possible.

I'm afraid I don't entirely understand the concern with the use case and the compatibility with Chrome's UX. The PTZ request should be able to be made even if you already have Camera without PTZ, but it's probably just me misunderstanding the use case or the concern.

**Comment by reillyeon** [comment]
> We have precedent in Chrome for delaying an automatic reply to a permission request to prevent deducing user state (in particular, notification permission requests in incognito). We can use that same approach here, if deemed necessary. Is the concern that this would help with fingerprinting users? I'm not very familiar with the media API so I'm not entirely sure how big the fingerprinting surface is already without PTZ and how much PTZ adds.

Delaying the automatic reply would resolve the fingerprinting concern but would mean a poor user experience as I am imagining the prompt would be displayed from an "enable PTZ" button in the site UI. The best user experience when clicking this button would be for it to change to a "Not supported by your device." state which requires letting the site know that the device does not support the capability, not that the user "denied" the prompt (but really they never saw it).

> On the other hand, presenting a user with a prompt for a capability they do not have seems like an unnecessary cognitive load, probably confusing and also different than how all other permissions work (you don't get camera prompts if you don't actually have a camera for example) and something that I would like to avoid if at all possible.

I wasn't aware that that was the case for general camera permission. In that case it may be reasonable to provide the PTZ constraint information before permission is requested. We should discuss this with the privacy reviewers.

**Comment by beaufortfrancois** [comment]
@reillyeon Did you have a chance to talk to the privacy reviewers?

**Comment by jan-ivar** [comment]
Why not require apps to be up front about requesting PTZ?

I think the spec should clarify that permission will only be requested as part of `getUserMedia` and not `applyConstraints`. If the PTZ constraints are seen in applyConstraints when PTZ permission is absent, treat as if the camera does not have the ability.

**Comment by guidou** [comment]
cc @alvestrand

**Comment by reillyeon** [comment]
> Why not require apps to be up front about requesting PTZ?

I think it depends on how important the PTZ capability is to the application and whether or not it already has camera permission. Requesting PTZ upfront in `getUserMedia()` will mean a permission request is shown before the video stream starts. This will be a regression for sites which already have camera permission. Allowing them to start the video stream and then request PTZ permission via `applyConstraints()` means that they can offer this as an opt-in to their users before showing a permission prompt. This allows the permission prompt to be displayed with better context for the user.

**Comment by andypaicu** [comment]
> > Why not require apps to be up front about requesting PTZ?
> 
> I think it depends on how important the PTZ capability is to the application and whether or not it already has camera permission. Requesting PTZ upfront in `getUserMedia()` will mean a permission request is shown before the video stream starts. This will be a regression for sites which already have camera permission. Allowing them to start the video stream and then request PTZ permission via `applyConstraints()` means that they can offer this as an opt-in to their users before showing a permission prompt. This allows the permission prompt to be displayed with better context for the user.

Could sites achieve the same result by first opening the stream without PTZ and then calling `getUserMedia` again with PTZ and replacing the existing video stream if the extra permission is granted? (I'm not very familiar with how `getUserMedia` is used so this is genuine question).

Overall I feel that allowing the permission to be requested mid-stream significantly muddies the permission model, in terms of how we expose the `pan`, `tilt`, `zoom` properties to developers, how we protect the user's privacy and how we avoid user prompt fatigue so I would prefer to go with: "`applyConstraints` can't result in a permission prompt, the PTZ properties are only exposed if the permission is provided at the time when `getUserMedia` was called".

**Comment by jan-ivar** [comment]
@andypaicu You're right, sites may achieve the same effect by calling `getUserMedia` again. It  shouldn't even require replacing the stream, since permission is per (top-level) document, not per stream. But doesn't that undermine the argument that the permission model remains simpler in any way by restricting it to `getUserMedia`?

**Comment by andypaicu** [comment]
> @andypaicu You're right, sites may achieve the same effect by calling `getUserMedia` again. It shouldn't even require replacing the stream, since permission is per (top-level) document, not per stream. But doesn't that undermine the argument that the permission model remains simpler in any way by restricting it to `getUserMedia`? (since it allows permission to be requested mid-stream)

While I suppose it's possible for the `pan`/`tilt`/`zoom` constraints to become available for the previously existing `MediaStreamTrack` object, I was actually envisioning an implementation where only the newly-obtained `MediaStreamTrack` object would have access to them. That is the sense in which I mean it simplifies the implementation model, the MediaStreamTrack object's ability to access/use PTZ would never change, you would just need to get an entirely new one.

If the mid-stream use case seems like something that is worth supporting, then I'm fine with allowing `allowConstraints` to request the permission, with the caveat that the constraints won't actually be available to the developer before so they would have to use the `{pan: true, tilt: true, zoom: true}` syntax first (since they can't provide meaningful constraints in the first place).

**Comment by jan-ivar** [comment]
> with the caveat that the constraints won't actually be available to the developer before so they would have to use the {pan: true, tilt: true, zoom: true} syntax first (since they can't provide meaningful constraints in the first place).

Good point. Yes you'd have the same limitation there as with calling `getUserMedia` again. E.g.
```js
let pan = track.getSettings().pan; // undefined
if (pan === undefined) {
  await track.applyConstraints({pan: true}); // permission elevation prompt
  pan = track.getSettings().pan; // actual value revealed (if supported)
}
```
This would be important to not reveal more fingerprinting info than permitted.

**Comment by andypaicu** [comment]
Also developers would have to keep track that they have requested PTZ and it was denied/unavailable since I suspect that they don't want to repeatedly run through that pattern whenever they might want to do something with `pan`,`tilt` and `zoom`. The fact that `pan`, `tilt`, `zoom` being undefined could either mean `you're denied/feature unavailable` or `you have not requested the permissions yet, give a try perhaps` makes writing the code somewhat cumbersome IMO.

I suspect developers would end up doing something like this:
```
let pan = track.getSettings().pan; // undefined
if (pan === undefined) {
  await track.applyConstraints({pan: true}); // permission elevation prompt
  pan = track.getSettings().pan; // actual value revealed (if supported)
}
let ptz_available = (pan !== undefined);
// And from now on, rely on ptz_available instead of doing `pan !== undefined`
```

Of course, in contrast the other proposal also has downsides in terms of cumbersomeness since it will require re-calling `getUserMedia` and replacing your stream. But OTOH it means that `pan === undefined` will always mean `you're denied/feature unavailable` (in a stream that was obtained with a PTZ-enabling `getUserMedia` call). Mentally that makes more sense to me. Practically I don't know if any approach has a clear edge so at this point I'm happy either way.

**Comment by beaufortfrancois** [comment]
I'd be in favor of not prompting user in `applyConstraints` for simplicity. If web developers come back to us and claim that this is a requirement, we can still add it later. WDYT?

**Comment by beaufortfrancois** [comment]
Based on feedback, I've filed a PR at https://github.com/w3c/mediacapture-image/pull/227

**Comment by beaufortfrancois** [comment]
I'll close this issue.
