### ISSUE TITLE
Control over the image format?

### ISSUE THREAD

**Issue by dandv** [w3c/mediacapture-image#72]
I'm writing a [polyfill for ImageCapture](https://github.com/dandv/imagecapture), and the fact that grabFrame() and takePhoto() return different image formats (ImageBitmap vs. Blob) seems unjustified (what I mean is there might be good reasons for this; just that I couldn't find them in the spec).

Proposal: allow the developer to control the format returned by the two methods.

**Comment by gmandyam** [comment]
@dandv.  Appreciate the feedback.  Yes, there is no explanation in the document, so I'll try to provide one here.  grabFrame() resulted from a proposal several years ago (https://lists.w3.org/Archives/Public/public-media-capture/2013Feb/0099.html) to provide a companion API to takePhoto() that would essentially allow for real-time processing of the capture stream.  

Ironically, the proposer wanted to avoid timers, which grabFrame() doesn't really provide.  This was due to browser vendors preference for a one-shot API.  

As to the difference between ImageBitmap and Blob, the Blob data type is encoded.  This means that JS must decode in order to access/manipulate the underlying image data.  ImageBitmap allows for direct manipulation of the underlying image data (e.g. through createImageBitmap) without having to decode.  Moreover, the browser (based on my understanding) only keeps a reference to the bitmap while the underlying data remains with the GPU.  This allows for very fast rendering to a <canvas> element.

**Comment by beaufortfrancois** [comment]
Can we please add this explanation to the spec as it helps understanding the API? Thank you for writing this @gmandyam!

**Comment by miguelao** [comment]
@beaufortfrancois: part of this is now in the spec, e.g. for grabFrame() it says 

>... grabFrame() takes a snapshot of the live video being held in the videoStreamTrack, returning an ImageBitmap if successful.

and for takePhoto():

>... takePhoto() produces the result of a single photographic exposure using the video capture device sourcing the videoStreamTrack, applying any PhotoSettings previously configured, and returning an encoded image in the form of a Blob if successful.

And I'll add a note somewhere contrasting one and the other and their underlying data types.

**Comment by miguelao** [comment]
Looking better after #100?

**Comment by miguelao** [comment]
Preventively closing per #100.
